// Builds docs/SLIDES-team.html from docs/SLIDES.html: the same deck with every speaker note
// removed and the notes panel disabled, for sharing with attendees. Run before build.mjs --team.
import { readFileSync, writeFileSync } from 'node:fs'
import { resolve, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '../..')
const SRC = resolve(root, 'docs/SLIDES.html')
const OUT = resolve(root, 'docs/SLIDES-team.html')

let html = readFileSync(SRC, 'utf8')
const before = (html.match(/<div class="notes-src">/g) || []).length
html = html.replace(/\s*<div class="notes-src">[\s\S]*?<\/div>\s*(?=<\/section>)/g, '\n')
html = html.replace(/<aside id="notes"[^>]*>[\s\S]*?<\/aside>/, '<aside id="notes" hidden><div id="notes-body"></div></aside>')
html = html.replace(/ &nbsp;·&nbsp; <b>N<\/b> notes/, '')
html = html.replace(/\s*else if \(e\.key === 'n' \|\| e\.key === 'N'\) \{[^\n]*\n/, '\n')
html = html.replace('<!doctype html>', '<!doctype html>\n<!-- Generated by tools/pptx/team-deck.mjs from SLIDES.html. Edit SLIDES.html, not this file. -->')
const after = (html.match(/<div class="notes-src">/g) || []).length
writeFileSync(OUT, html)
console.log(`wrote ${OUT}: removed ${before} notes blocks, ${after} left`)
